services:
  chrony:
    image: ghcr.io/theaustrian75/gpsntp:latest
    build:
      context: .
      dockerfile: Dockerfile.gpsntp
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /etc/chrony:rw,mode=1750
      - /run/chrony:rw,mode=1750
      - /var/lib/chrony:rw,mode=1750
    network_mode: host
    cap_add:
      - SYS_TIME
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0:rw
      - /dev/pps0:/dev/pps0:rw
      - /dev/ptp0:/dev/ptp0:rw
    environment:
      NTP_SERVERS: "${NTP_SERVERS:?Set NTP_SERVERS in .env}"
      NTP_ALLOW: "${NTP_ALLOW?Set NTP_ALLOW in .env}"
      LOG_LEVEL: "${LOG_LEVEL:?Set LOG_LEVEL in .env}"
      TZ: "${TZ:?Set TZ in .env}"
      NOCLIENTLOG: "${NOCLIENTLOG:?Set NOCLIENTLOG in .env}"
      ENABLE_NTS: "${ENABLE_NTS:?Set ENABLE_NTS in .env}"
      ENABLE_SYSCLK: "${ENABLE_SYSCLK:?Set ENABLE_SYSCLK in .env}"
