#!/bin/bash

set -Eeuo pipefail

readonly DEFAULT_NTP="0.pool.ntp.org,1.pool.ntp.org,2.pool.ntp.org,3.pool.ntp.org"
readonly DEFAULT_PPS="pps0"
readonly DEFAULT_TTY="ttyAMA0"
readonly CHRONY_CONF_FILE="/etc/chrony/chrony.conf"

NTP_SERVERS="${NTP_SERVERS:-${DEFAULT_NTP}}"
NTP_ALLOW="${NTP_ALLOW-all}"
DEV_PPS="${DEV_PPS:-}"
DEV_TTY="${DEV_TTY:-}"
LOG_LEVEL="${LOG_LEVEL:-0}"

# confirm correct permissions on chrony run directory
mkdir -p /etc/chrony /run/chrony /var/lib/chrony
chown chrony:chrony /run/chrony /var/lib/chrony
chmod 0750 /run/chrony

# Remove a stale PID file left by an unclean shutdown
rm -f /run/chrony/chronyd.pid

# Dynamically populate the chrony configuration file
{
  echo "# https://github.com/simonrupf/docker-chrony"
  echo
  echo "# chrony.conf file generated by startup script"
  echo "# located at $0"
  echo
  echo "# time servers provided by the NTP_SERVERS environment variable."
} > "${CHRONY_CONF_FILE}"

# Figure out which hardware devices we can use
for device in "${DEV_PPS}" "${DEV_TTY}"; do
  if [[ -n "${device}" && ! "${device}" =~ ^[A-Za-z0-9._-]+$ ]]; then
    echo "Invalid device name '${device}'; provide a basename under /dev" >&2
    exit 1
  fi
done

if [[ -z "${DEV_PPS}" && -e "/dev/${DEFAULT_PPS}" ]]; then
  DEV_PPS="${DEFAULT_PPS}"
  echo "Using /dev/${DEV_PPS}"
elif [[ -n "${DEV_PPS}" && ! -e "/dev/${DEV_PPS}" ]]; then
  echo "PPS: /dev/${DEV_PPS} does not exist"
  exit 1
fi

if [[ -z "${DEV_TTY}" && -e "/dev/${DEFAULT_TTY}" ]]; then
  DEV_TTY="${DEFAULT_TTY}"
  echo "Using /dev/${DEV_TTY}"
elif [[ -n "${DEV_TTY}" && ! -e "/dev/${DEV_TTY}" ]]; then
  echo "TTY: /dev/${DEV_TTY} does not exist"
  exit 1
fi

# Chrony supports log levels 0 (informational) through 3 (fatal)
case "${LOG_LEVEL}" in
  0|1|2|3) ;;
  *)
    echo "Invalid LOG_LEVEL '${LOG_LEVEL}'; using 0" >&2
    LOG_LEVEL=0
    ;;
esac

IFS=',' read -ra ntp_servers <<< "${NTP_SERVERS}"
for server in "${ntp_servers[@]}"; do
  # Strip surrounding whitespace
  server="$(printf '%s' "${server}" | xargs)"
  [[ -n "${server}" ]] || continue

  # Server values become chrony directives, so accept only host/address characters.
  if [[ ! "${server}" =~ ^[A-Za-z0-9._:-]+$ ]]; then
    echo "Invalid NTP server '${server}'" >&2
    exit 1
  fi

  # A 127.0.0.0/8 address indicates the local system clock
  if [[ "${server}" == 127.* ]]; then
    echo "server ${server}" >> "${CHRONY_CONF_FILE}"
    echo "local stratum 10" >> "${CHRONY_CONF_FILE}"
  else
    if [[ "${ENABLE_NTS:-false}" == "true" ]]; then
      echo "server ${server} iburst nts" >> "${CHRONY_CONF_FILE}"
    else
      echo "server ${server} iburst" >> "${CHRONY_CONF_FILE}"
    fi
  fi
done

# Set up GPS time sources
# - PPS is the most accurate (nanoseconds)
# - SHM 0 from gpsd is the NMEA data at 4800bps, so it is not very accurate
# - SOCK protocol includes PPS data and provides time within a few ns
if [[ -n "${DEV_PPS}" ]]; then
  echo "refclock PPS /dev/${DEV_PPS} refid PPS poll 0 delay 0.0 filter 80 precision 1e-9" >> "${CHRONY_CONF_FILE}"
fi

if [[ -n "${DEV_TTY}" ]]; then
  echo "refclock SHM 0 precision 1e-1 offset 0.628 delay 0.5 refid UBLX noselect" >> "${CHRONY_CONF_FILE}"
  echo "refclock SOCK /var/run/chrony.${DEV_TTY}.sock poll 0 delay 0.0 refid SOCK" >> "${CHRONY_CONF_FILE}"
fi

# PTP0 configuration: if it has been passed through, it means we want to use it
if [[ -e /dev/ptp0 ]]; then
  echo "refclock PHC /dev/ptp0 poll 3 dpoll -2 stratum 2" >> "${CHRONY_CONF_FILE}"
fi

# Add the final configuration directives
{
  echo
  echo "driftfile /var/lib/chrony/chrony.drift"
  echo "makestep 0.1 3"
  if [[ -n "${NTP_DIRECTIVES:-}" ]]; then
    printf '%b\n' "${NTP_DIRECTIVES}"
  fi
  if [[ "${NOCLIENTLOG:-false}" == "true" ]]; then
    echo "noclientlog"
  fi

  # Set NTP_ALLOW to an empty value to disable remote NTP clients, or to a
  # subnet such as 192.168.1.0/24 to restrict access.
  if [[ -n "${NTP_ALLOW}" ]]; then
    if [[ ! "${NTP_ALLOW}" =~ ^[A-Za-z0-9.:/-]+$ ]]; then
      echo "Invalid NTP_ALLOW network '${NTP_ALLOW}'" >&2
      exit 1
    fi
    echo
    echo "allow ${NTP_ALLOW}"
  fi
} >> "${CHRONY_CONF_FILE}"

chronyd_args=(-u chrony -d -L "${LOG_LEVEL}")
if [[ "${ENABLE_SYSCLK:-false}" != "true" ]]; then
  # Disable system-clock control unless explicitly enabled.
  chronyd_args+=(-x)
fi

# Keep Bash as PID 1 so it can supervise both daemons and forward signals.
pids=()
terminate() {
  local pid
  for pid in "${pids[@]}"; do
    kill -TERM "${pid}" 2>/dev/null || true
  done
}
trap terminate TERM INT

if [[ -n "${DEV_TTY}" ]]; then
  gpsd_devices=("/dev/${DEV_TTY}")
  if [[ -n "${DEV_PPS}" ]]; then
    gpsd_devices+=("/dev/${DEV_PPS}")
  fi
  /usr/sbin/gpsd -rnbN "${gpsd_devices[@]}" &
  pids+=("$!")
fi

/usr/sbin/chronyd "${chronyd_args[@]}" &
pids+=("$!")

# If either daemon exits, stop the other and return the first exit status.
status=0
wait -n "${pids[@]}" || status=$?
terminate
for pid in "${pids[@]}"; do
  wait "${pid}" 2>/dev/null || true
done
exit "${status}"
